version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    depends_on:
      - db
    volumes:
      - ./public/files:/app/public/files

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: cron/Dockerfile
    restart: always
    command: node cronjob.js
    depends_on:
      - server

  db:
    image: mysql:8.2.0
    container_name: db
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: 'devicemanager'
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - 'dbdata:/var/lib/mysql'

volumes:
  dbdata:
