version: '3.8'

services:
  server:
    container_name: device-manager-server
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  cron:
    container_name: device-manager-cron
    build:
      context: ./cron
    restart: always
    command: node cronJob.js
    depends_on:
      - server

  db:
    image: mysql:8.2.0
    container_name: device-manager-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'devicemanager'
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - 'dbdata:/var/lib/mysql'

volumes:
  dbdata:
